/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestimonialImport } from './routes/testimonial'
import { Route as TeamImport } from './routes/team'
import { Route as ServiceImport } from './routes/service'
import { Route as PricingImport } from './routes/pricing'
import { Route as OpenImport } from './routes/open'
import { Route as ContentImport } from './routes/content'
import { Route as ContactImport } from './routes/contact'
import { Route as AppointmentImport } from './routes/appointment'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TestimonialRoute = TestimonialImport.update({
  path: '/testimonial',
  getParentRoute: () => rootRoute,
} as any)

const TeamRoute = TeamImport.update({
  path: '/team',
  getParentRoute: () => rootRoute,
} as any)

const ServiceRoute = ServiceImport.update({
  path: '/service',
  getParentRoute: () => rootRoute,
} as any)

const PricingRoute = PricingImport.update({
  path: '/pricing',
  getParentRoute: () => rootRoute,
} as any)

const OpenRoute = OpenImport.update({
  path: '/open',
  getParentRoute: () => rootRoute,
} as any)

const ContentRoute = ContentImport.update({
  path: '/content',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AppointmentRoute = AppointmentImport.update({
  path: '/appointment',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentImport
      parentRoute: typeof rootRoute
    }
    '/open': {
      id: '/open'
      path: '/open'
      fullPath: '/open'
      preLoaderRoute: typeof OpenImport
      parentRoute: typeof rootRoute
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingImport
      parentRoute: typeof rootRoute
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceImport
      parentRoute: typeof rootRoute
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamImport
      parentRoute: typeof rootRoute
    }
    '/testimonial': {
      id: '/testimonial'
      path: '/testimonial'
      fullPath: '/testimonial'
      preLoaderRoute: typeof TestimonialImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/open': typeof OpenRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/open': typeof OpenRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/open': typeof OpenRoute
  '/pricing': typeof PricingRoute
  '/service': typeof ServiceRoute
  '/team': typeof TeamRoute
  '/testimonial': typeof TestimonialRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/content'
    | '/open'
    | '/pricing'
    | '/service'
    | '/team'
    | '/testimonial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/content'
    | '/open'
    | '/pricing'
    | '/service'
    | '/team'
    | '/testimonial'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/content'
    | '/open'
    | '/pricing'
    | '/service'
    | '/team'
    | '/testimonial'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  OpenRoute: typeof OpenRoute
  PricingRoute: typeof PricingRoute
  ServiceRoute: typeof ServiceRoute
  TeamRoute: typeof TeamRoute
  TestimonialRoute: typeof TestimonialRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  OpenRoute: OpenRoute,
  PricingRoute: PricingRoute,
  ServiceRoute: ServiceRoute,
  TeamRoute: TeamRoute,
  TestimonialRoute: TestimonialRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/appointment",
        "/contact",
        "/content",
        "/open",
        "/pricing",
        "/service",
        "/team",
        "/testimonial"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/appointment": {
      "filePath": "appointment.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/content": {
      "filePath": "content.tsx"
    },
    "/open": {
      "filePath": "open.tsx"
    },
    "/pricing": {
      "filePath": "pricing.tsx"
    },
    "/service": {
      "filePath": "service.tsx"
    },
    "/team": {
      "filePath": "team.tsx"
    },
    "/testimonial": {
      "filePath": "testimonial.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
